Traceback (most recent call last):
  File "game/scripts/2/1/3/32.rpy", line 10004, in script
    with open('archives/hina.chr', 'rb+') as hina:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'archives/hina.chr'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "game/scripts/2/1/3/32.rpy", line 10005, in script
    with open('archives/hoshino.chr', 'rb+') as hoshino:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'archives/hoshino.chr'